---
- name: Install a specified package on Ubuntu 22.04
  hosts: ubuntu_workspaces
  become: yes

  tasks:
    - name: Update apt repository cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install specified package
      ansible.builtin.apt:
        name: "{{ package_name }}"
        state: present